// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config-service.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_FAILED Status = 0
	Status_OK     Status = 1
)

var Status_name = map[int32]string{
	0: "FAILED",
	1: "OK",
}
var Status_value = map[string]int32{
	"FAILED": 0,
	"OK":     1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_config_service_f16a4c1a13019161, []int{0}
}

type Instance struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Domain               string   `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_service_f16a4c1a13019161, []int{0}
}
func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (dst *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(dst, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Instance) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Instance) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type ConfigUpdateRequest struct {
	Api                  string    `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Deployment           *Instance `protobuf:"bytes,2,opt,name=deployment,proto3" json:"deployment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConfigUpdateRequest) Reset()         { *m = ConfigUpdateRequest{} }
func (m *ConfigUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigUpdateRequest) ProtoMessage()    {}
func (*ConfigUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_service_f16a4c1a13019161, []int{1}
}
func (m *ConfigUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigUpdateRequest.Unmarshal(m, b)
}
func (m *ConfigUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigUpdateRequest.Marshal(b, m, deterministic)
}
func (dst *ConfigUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigUpdateRequest.Merge(dst, src)
}
func (m *ConfigUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigUpdateRequest.Size(m)
}
func (m *ConfigUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigUpdateRequest proto.InternalMessageInfo

func (m *ConfigUpdateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ConfigUpdateRequest) GetDeployment() *Instance {
	if m != nil {
		return m.Deployment
	}
	return nil
}

type ConfigUpdateResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               Status   `protobuf:"varint,2,opt,name=status,proto3,enum=v1.Status" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigUpdateResponse) Reset()         { *m = ConfigUpdateResponse{} }
func (m *ConfigUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigUpdateResponse) ProtoMessage()    {}
func (*ConfigUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_service_f16a4c1a13019161, []int{2}
}
func (m *ConfigUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigUpdateResponse.Unmarshal(m, b)
}
func (m *ConfigUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigUpdateResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigUpdateResponse.Merge(dst, src)
}
func (m *ConfigUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigUpdateResponse.Size(m)
}
func (m *ConfigUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigUpdateResponse proto.InternalMessageInfo

func (m *ConfigUpdateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ConfigUpdateResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_FAILED
}

func (m *ConfigUpdateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Instance)(nil), "v1.Instance")
	proto.RegisterType((*ConfigUpdateRequest)(nil), "v1.ConfigUpdateRequest")
	proto.RegisterType((*ConfigUpdateResponse)(nil), "v1.ConfigUpdateResponse")
	proto.RegisterEnum("v1.Status", Status_name, Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigServiceClient interface {
	Create(ctx context.Context, in *ConfigUpdateRequest, opts ...grpc.CallOption) (*ConfigUpdateResponse, error)
	Update(ctx context.Context, in *ConfigUpdateRequest, opts ...grpc.CallOption) (*ConfigUpdateResponse, error)
	Delete(ctx context.Context, in *ConfigUpdateRequest, opts ...grpc.CallOption) (*ConfigUpdateResponse, error)
}

type configServiceClient struct {
	cc *grpc.ClientConn
}

func NewConfigServiceClient(cc *grpc.ClientConn) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) Create(ctx context.Context, in *ConfigUpdateRequest, opts ...grpc.CallOption) (*ConfigUpdateResponse, error) {
	out := new(ConfigUpdateResponse)
	err := c.cc.Invoke(ctx, "/v1.ConfigService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) Update(ctx context.Context, in *ConfigUpdateRequest, opts ...grpc.CallOption) (*ConfigUpdateResponse, error) {
	out := new(ConfigUpdateResponse)
	err := c.cc.Invoke(ctx, "/v1.ConfigService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) Delete(ctx context.Context, in *ConfigUpdateRequest, opts ...grpc.CallOption) (*ConfigUpdateResponse, error) {
	out := new(ConfigUpdateResponse)
	err := c.cc.Invoke(ctx, "/v1.ConfigService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
type ConfigServiceServer interface {
	Create(context.Context, *ConfigUpdateRequest) (*ConfigUpdateResponse, error)
	Update(context.Context, *ConfigUpdateRequest) (*ConfigUpdateResponse, error)
	Delete(context.Context, *ConfigUpdateRequest) (*ConfigUpdateResponse, error)
}

func RegisterConfigServiceServer(s *grpc.Server, srv ConfigServiceServer) {
	s.RegisterService(&_ConfigService_serviceDesc, srv)
}

func _ConfigService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ConfigService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).Create(ctx, req.(*ConfigUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ConfigService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).Update(ctx, req.(*ConfigUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ConfigService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).Delete(ctx, req.(*ConfigUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfigService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ConfigService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ConfigService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ConfigService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config-service.proto",
}

func init() {
	proto.RegisterFile("config-service.proto", fileDescriptor_config_service_f16a4c1a13019161)
}

var fileDescriptor_config_service_f16a4c1a13019161 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xdf, 0x4a, 0xeb, 0x40,
	0x10, 0xc6, 0x4f, 0x5a, 0xd8, 0x73, 0x3a, 0x47, 0x4b, 0x59, 0x8b, 0x06, 0xe9, 0x85, 0xe4, 0x4a,
	0x44, 0x17, 0x1a, 0x2f, 0x7b, 0x65, 0x5b, 0x85, 0xfa, 0x07, 0x21, 0xa5, 0x0f, 0x30, 0x26, 0xd3,
	0x10, 0x69, 0x66, 0x63, 0x76, 0x1b, 0xec, 0x0b, 0xfa, 0x5c, 0x92, 0x3f, 0x45, 0xc5, 0x5e, 0xf5,
	0x6e, 0xe6, 0xfb, 0x32, 0xbf, 0xf9, 0xb2, 0x0c, 0xf4, 0x43, 0xcd, 0xcb, 0x24, 0xbe, 0x32, 0x94,
	0x17, 0x49, 0x48, 0x2a, 0xcb, 0xb5, 0xd5, 0xb2, 0x55, 0x0c, 0xbd, 0x00, 0xfe, 0xcd, 0xd8, 0x58,
	0xe4, 0x90, 0xe4, 0x00, 0x3a, 0x8c, 0x29, 0x99, 0x0c, 0x43, 0x72, 0x9d, 0x33, 0xe7, 0xbc, 0x13,
	0x7c, 0x09, 0xb2, 0x07, 0xed, 0x75, 0x12, 0xb9, 0xad, 0x4a, 0x2f, 0x4b, 0x79, 0x0c, 0x22, 0xd2,
	0x29, 0x26, 0xec, 0xb6, 0x2b, 0xb1, 0xe9, 0xbc, 0x05, 0x1c, 0x4d, 0xaa, 0x7d, 0x8b, 0x2c, 0x42,
	0x4b, 0x01, 0xbd, 0xad, 0xc9, 0xd8, 0x12, 0x80, 0x59, 0xd2, 0x80, 0xcb, 0x52, 0x5e, 0x02, 0x44,
	0x94, 0xad, 0xf4, 0x26, 0x25, 0xb6, 0x15, 0xf9, 0xbf, 0x7f, 0xa0, 0x8a, 0xa1, 0xda, 0x46, 0x0a,
	0xbe, 0xf9, 0xde, 0x12, 0xfa, 0x3f, 0xb1, 0x26, 0xd3, 0x6c, 0x68, 0x07, 0xd7, 0x03, 0x61, 0x2c,
	0xda, 0xb5, 0xa9, 0x98, 0x5d, 0x1f, 0x4a, 0xe6, 0xbc, 0x52, 0x82, 0xc6, 0x91, 0x2e, 0xfc, 0x4d,
	0xc9, 0x18, 0x8c, 0xa9, 0x49, 0xbf, 0x6d, 0x2f, 0x06, 0x20, 0xea, 0x6f, 0x25, 0x80, 0xb8, 0xbb,
	0x99, 0x3d, 0xde, 0x4e, 0x7b, 0x7f, 0xa4, 0x80, 0xd6, 0xf3, 0x43, 0xcf, 0xf1, 0x3f, 0x1c, 0x38,
	0xac, 0x63, 0xcc, 0xeb, 0xc7, 0x94, 0x23, 0x10, 0x93, 0x9c, 0xd0, 0x92, 0x3c, 0x29, 0xf7, 0xec,
	0xf8, 0xf5, 0x53, 0xf7, 0xb7, 0xd1, 0x84, 0x1f, 0x81, 0xa8, 0x95, 0x3d, 0x87, 0xa7, 0xb4, 0xa2,
	0xbd, 0x86, 0xc7, 0x53, 0xf0, 0x99, 0xac, 0x8a, 0x09, 0xd9, 0x2a, 0x4e, 0x11, 0x8d, 0xa2, 0x77,
	0x4b, 0x39, 0xe3, 0xaa, 0x39, 0x13, 0xa3, 0x12, 0x2e, 0x88, 0xad, 0xce, 0x37, 0xea, 0x15, 0x39,
	0xb1, 0x3a, 0x1f, 0x77, 0xef, 0xeb, 0xe2, 0x09, 0x19, 0x63, 0xca, 0x5f, 0x44, 0x75, 0x4a, 0xd7,
	0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x84, 0x11, 0xfd, 0x62, 0x02, 0x00, 0x00,
}
