name: Build and unit test

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19'

      - name: Verify Go version
        run: go version

      - name: Run tests
        run: go test
