name: Build and unit test

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Set up GO
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19'
        run: go version

      - name: Build with Gradle
        run: go test
